# Generated by Django 5.2 on 2025-06-25 14:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habito', '0003_habito_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='habito',
            name='data',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
